name: KiCad manufacturing check

on:
  workflow_dispatch:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'

permissions:
  contents: write # To pozwala botowi zapisać pliki w głównym oknie!

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run ERC (Test schematu)
        shell: bash
        run: |
          set +e
          if [ -f "pcb-psu-led.kicad_sch" ]; then
            docker run --rm \
              -v "$GITHUB_WORKSPACE:/work" \
              -w /work \
              kicad/kicad:9.0 \
              kicad-cli sch erc \
                --severity-all \
                --output reports/erc.rpt \
                pcb-psu-led.kicad_sch
          else
            echo "Brak pliku pcb-psu-led.kicad_sch" > reports/erc.rpt
          fi

      - name: Run DRC (Test plytki)
        shell: bash
        run: |
          set +e
          if [ -f "pcb-psu-led.kicad_pcb" ]; then
            docker run --rm \
              -v "$GITHUB_WORKSPACE:/work" \
              -w /work \
              kicad/kicad:9.0 \
              kicad-cli pcb drc \
                --severity-all \
                --output reports/drc.rpt \
                pcb-psu-led.kicad_pcb
          else
            echo "Brak pliku pcb-psu-led.kicad_pcb" > reports/drc.rpt
          fi

      - name: Wrzucenie raportu do glownego okna (Push)
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/
          git commit -m "Automatyczna aktualizacja raportów KiCad" || echo "Brak zmian"
          git push origin HEAD:main
